[listen]
ssl = false
cert = "wildcard_certificate"
key = "wildcard_key"
port = 8081

[remote]
port = 8080

[ldap]
useldap = false
host = "ldap.example.com"
port = 389
base = "cn=users,cn=accounts,dc=example,dc=com"
groupbase = "cn=groups,cn=accounts,dc=example,dc=com"
binddn = "cn=users,cn=accounts,dc=example,dc=com"
bindpassword = "some password"

[tv]

	[tv.hqtv1]
	name = "TV 1"
	host = "localhost"

	[tv.hqtv2]
	name = "TV 2"
	host = "tv2"

	[tv.hqtv3]
	name = "TV 3"
	host = "tv3"
